version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: banking-backend
    ports:
      - "8000:8000"
    environment:
      INTENT_SERVICE_HOST: intent-service
      INTENT_SERVICE_PORT: 50051
      OLLAMA_BASE_URL: https://hdwrr-8-231-187-122.run.pinggy-free.link
      OLLAMA_MODEL_NAME: ${OLLAMA_MODEL_NAME:-gpt-oss:20b}
    depends_on:
      - intent-service
    networks:
      - public_net
      - internal_net
    restart: unless-stopped

  intent-service:
    build:
      context: ./intent_service
      dockerfile: Dockerfile
    container_name: intent-service
    ports:
      - "50051:50051"
    environment:
      OLLAMA_BASE_URL: https://hdwrr-8-231-187-122.run.pinggy-free.link
      INTENT_MODEL_NAME: ${INTENT_MODEL_NAME:-gpt-oss:20b}
      GRPC_PORT: 50051
    networks:
      - internal_net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: banking-frontend
    ports:
      - "8501:8501"
    environment:
      API_BASE_URL: http://backend:8000
    depends_on:
      - backend
    networks:
      - public_net
    restart: unless-stopped

networks:
  public_net:
    name: banking_public_net
  internal_net:
    name: banking_internal_net
