"""gRPC server for Banking Intent Classification Service."""

import asyncio
import logging
import signal
import sys

import grpc
from grpc import aio

# These modules are auto-generated by `make` from intent_service.proto
import intent_service_pb2
import intent_service_pb2_grpc

from app.core.settings import get_settings
from app.nodes.intent_node import classify

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("intent_service")


class IntentServiceServicer(intent_service_pb2_grpc.IntentServiceServicer):
    """gRPC servicer that handles intent classification requests."""

    async def IntentRecognizer(self, request, context):
        """Classify the intent of a customer message.

        Args:
            request: IntentRequest with a message field.
            context: gRPC context.

        Returns:
            IntentResponse with intent, confidence, and reason.
        """
        user_message = request.message
        logger.info("Received intent request: '%s'", user_message[:100])

        if not user_message.strip():
            context.set_code(grpc.StatusCode.INVALID_ARGUMENT)
            context.set_details("Message cannot be empty")
            return intent_service_pb2.IntentResponse()

        try:
            # Run classification (sync function) in executor to not block event loop
            loop = asyncio.get_event_loop()
            result = await loop.run_in_executor(None, classify, user_message)

            logger.info(
                "Classification result: intent=%s, confidence=%.2f",
                result.intent,
                result.confidence,
            )

            return intent_service_pb2.IntentResponse(
                intent=result.intent,
                confidence=result.confidence,
                reason=result.reason,
            )

        except Exception as e:
            logger.error("Classification error: %s", e, exc_info=True)
            context.set_code(grpc.StatusCode.INTERNAL)
            context.set_details(f"Intent classification failed: {str(e)}")
            return intent_service_pb2.IntentResponse()


async def serve():
    """Start the gRPC server."""
    settings = get_settings()
    port = settings.GRPC_PORT

    server = aio.server()
    intent_service_pb2_grpc.add_IntentServiceServicer_to_server(
        IntentServiceServicer(), server
    )
    server.add_insecure_port(f"[::]:{port}")

    await server.start()
    logger.info("=" * 60)
    logger.info("Intent Service gRPC server started on port %d", port)
    logger.info("Ollama URL: %s", settings.OLLAMA_BASE_URL)
    logger.info("Model: %s", settings.INTENT_MODEL_NAME)
    logger.info("=" * 60)

    # Graceful shutdown handling
    async def shutdown(sig):
        logger.info("Received signal %s, shutting down...", sig.name)
        await server.stop(grace=5)

    loop = asyncio.get_event_loop()
    if sys.platform != "win32":
        for sig in (signal.SIGINT, signal.SIGTERM):
            loop.add_signal_handler(
                sig, lambda s=sig: asyncio.create_task(shutdown(s))
            )

    try:
        await server.wait_for_termination()
    except KeyboardInterrupt:
        logger.info("Keyboard interrupt received, shutting down...")
        await server.stop(grace=5)


if __name__ == "__main__":
    asyncio.run(serve())
